/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TStepItem: typeof import('tdesign-vue-next')['StepItem']
    TSteps: typeof import('tdesign-vue-next')['Steps']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
